spring:
  datasource:
    url: jdbc:mysql://localhost:13306/mealtracker?useSSL=false&useTimezone=true&serverTimezone=UTC
    username: root
    password: 8&pqA24iyQ01
  jpa:
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.MySQL5Dialect

logging:
  level:
    org:
      hibernate:
        SQL:
          TRACE
        type:z
          descriptor:
            sql:
              BasicBinder:
                TRACE
